version: 2
updates:

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "uv"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
