tools:
  # we want to use a pinned version of binny to manage the toolchain (so binny manages itself!)
  - name: binny
    version:
      want: v0.8.0
    method: github-release
    with:
      repo: anchore/binny

  # used for showing the changelog at release
  - name: glow
    version:
      want: v2.0.0
    method: github-release
    with:
      repo: charmbracelet/glow

  # used at release to generate the changelog
  - name: chronicle
    version:
      want: v0.8.0
    method: github-release
    with:
      repo: anchore/chronicle
